spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_alpha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181
  #SSL证书（可选）
  #ssl:
  #  key-store: classpath:
  #  key-store-password:
  #  key-store-type: JKS
#RSA私钥
key:
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCfvQ+povFLjlMTfRONP74MXAbteyv7t8dAkTcjzNwTiQrKeFJoCk55LpISzDxrKBuat30ad7xG7rSFzsnb6Cq4NscagYxuitAdCP2dfg8TI8Rcc8zYOXaOcuNSjy5rvwE4d5Glz3kG/Uw2/hlAz8bOCTrz+1JfS5t4hMcwN0dCs2tk6zHv+gJzUHmueKdTpGf75yI0JO46y+aM1EYPHEf75UBHRyphGhlFMSg+dEAtDsrFz0SoxmTOhTY8Sa/GraVQ6UBHMh7xGpUU60dymGe8Qhd+hvpYs2vGHTkYszqdf2Ppip99l7N24IEZpXBRAkNdz614bGi0t3ULETG6jZGzAgMBAAECggEBAJcHnqN5WENj0dB/VdkbB4mQCUzIRJG+9TlrE4NZ0kr2K6m7kc6k0AVrrtjvGcEHLvJdwn8f7nfygeRx3BF7tchuolnBWxG5VYPeWExsP7yM+L+hDXDzA9EzdxM8JVviQDkvdBodzAR7wW/NV/sbeJCd0YuVeBB54AlXIS3JVisNEj7mlymVhr4PYVyeyPh+L6+Egs8MU5M7B5jnLx8EUXnlmI4lyPGjjFBSzd3Djj5BmSr31TaBrxZ/sZhA2Aql42GytxuuUHqEvVP6aAypPBdhzdlMduv+PdJv3k+9TjlhBeGH17xcj+ArxgrYy8rfU1i2MFgs9CRfdfJM3ZQe4QECgYEA0Xpj7Yigdid/oR0iFU48/Ekj5MwOq9xxu7NWK4CelLBHU+VT5/cKxF4/gmS+z182esA50c4lNzcHevew5oP4B6ZOZSLFNzQB85b/3I1j5D2ID1sN+2JkocILI87x7N0//xjyRc3xMzK3eUzxOY3oNFiHrMn/UElvNvXBv7+H0JMCgYEAwzbKiO9nOuAokSCENTczEQO85qG/r8mG/W/qLo9m+bgHi7EQ0+SDcylIJqZKldSrtkfZCcHcsnlvlcmvV7KpyqayOFZksPgOEk9eI5c3Bb+MnTASfGgywQXqHvDU7ZwXq0UcYrmQiZE0ZBn7qQW4e0wJvvLjCcWUlO9nvRHCjmECgYEAx1LGMweGZ+c9snieLde8f/K4jMT+UNn5/riujcZdHu59cH8OT/Lp8+AaXmCuj3PxyuuOGO0mzFs4avG1CiMYp26/ucxUDCsYkEhmPd7r5goGpVXnAASn7KNPJkuMN+5vLrT2EyXbFPR1UJ6+Ch3VjbmPoAK1RhgaExnVujbtbLECgYBGyFAp1LyWgX7UGHk3nns6uSM+cPnDMIxsyq6cEU0iUNMTmLFkU2BCWn6Z3QQATeuxHV4aBpwSbqvCIS4d219rZoQKn3DFJjxb8UFOIF9IC0teF3cses+kY5Ofgm2Cdm2yoU2IkoZRC0B252DzyWo58rk57nHaMjUMx73StWTZIQKBgQC52e8dTmPW98eckVPbw+g0ieFDbCCdwvKHSo/tq68An6IVLsPOAHNPx0Zcmgfsmqw6X+AUU+j/wrfyomF7BK8Tnx+VtbTwEppyg+4NZgXcNRJ8m1qVl6q5ARXYPrF7lymaD89aSqIQEjj6ovYiIbm55HZPt1EBsGFR4laDHP+94g==